name: Latest Blog Posts

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest posts into README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://sudo3rs.medium.com/feed,https://ibliz-muda.blogspot.com/feeds/posts/default"
          max_post_count: 5
          template: "- [$title]($url) <sub>$date</sub><br>"
